project:
  type: website
  output-dir: docs

website:
  title: "**Ashley S. Ford** (aka *fordgeoscience*)"
  back-to-top-navigation: true
  navbar:
    search: true
    right:
      - href: index.qmd
      - about.qmd
      - research.qmd
      - cv.qmd
      - contact.qmd

format:
  html:
    title-block: false
    theme:
      - cosmos
    css: styles.css
    toc: true
    toc-location: right
    
runtime: shiny

editor: visual